---
- name: Setup access layer
  hosts: checkpoint
  tasks:
    - name: set-access-layer
      cp_mgmt_access_layer:
        applications_and_url_filtering: false
        content_awareness: true
        name: "ansible-demo-access-layer"
        firewall: true
        implicit_cleanup_action: drop
        mobile_access: true
        state: present
        auto_publish_session: true
