---
- name: Setup Access rule
  hosts: checkpoint

  vars:
    source_ip: "{{ hostvars['attacker']['private_ip2'] }}"
    destination_ip: "{{ hostvars['checkpoint']['private_ip2'] }}"

  tasks:
    - name: Create source IP host object
      cp_mgmt_host:
        name: "asa-{{ source_ip }}"
        ip_address: "{{ source_ip }}"
        auto_publish_session: true
    
    - name: Create destination IP host object
      cp_mgmt_host:
        name: "asa-{{ destination_ip }}"
        ip_address: "{{ destination_ip }}"
        auto_publish_session: true
    
    - name: Create access rule to allow access from source to destination
      cp_mgmt_access_rule:
        layer: Network
        position: top
        name: "asa-accept-{{ source_ip }}-to-{{ destination_ip }}"
        source: "asa-{{ source_ip }}"
        destination: "asa-{{ destination_ip }}"
        action: accept
        auto_publish_session: true
